name: musicfy

services:
  mongodb:
    restart:
      - on-failure:10
    image: mongo:7.0-jammy
    container_name: musicfy-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    networks:
      - backend_network

  backend:
    restart:
      - on-failure:10
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicfy-backend
    environment:
      - NODE_ENV=production
    networks:
      - backend_network
    depends_on:
      - mongodb
    ports:
      - "127.0.0.1:8080:8080"

secrets:
  db_password:
    file: db_password.txt

volumes:
  mongo_data:

networks:
  backend_network:
    driver: bridge
